### ISSUE TITLE
Brick Dictionary Textual Editor does not open

### ISSUE THREAD

**Issue by keller91711** [Impro-Visor/Impro-Visor#40]
Selecting the Brick Dictionary Textual Editor throws an exception. It tries to set a title on a button that does not exist.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at imp.roadmap.brickdictionary.BrickDictionaryEditorDialog.<init>(BrickDictionaryEditorDialog.java:61)
	at imp.roadmap.RoadMapFrame.openDictionaryEditor(RoadMapFrame.java:4811)

**Comment by keller91711** [comment]
Fixed in commit 802997af495f66eeb9207eeeefbda4733e337e95 on 13 August 2018.
