### ISSUE TITLE
Building Error in docker environment

### ISSUE THREAD

**Issue by fisheggg** [Impro-Visor/Impro-Visor#59]
Hi, thanks a lot for your work! Appreciated!

I encountered some problem when I try to build it with ant and ivy. 
My environment is ubuntu 18.04 and openjdk-8 on a docker image.

When I run `ant improvisor` in the home directory, it has an error of `501 HTTPS Required` sent by maven.org. It seems that the version of ivy that was downloaded is 2.1.0-rc2, which is quite old.
So I tried to manually change it to the latest version of ivy, 2.5.0, and then there's a display exception.  Although it says build successful, all the files in ./build are empty, and there's no executable file. Is there any way to skip this and build it in docker? Thanks very much!

ERROR using ivy2.1.0-rc2:
```
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          ::          UNRESOLVED DEPENDENCIES         ::
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          :: net.mikera#vectorz;0.48.0: not found
[ivy:retrieve]          :: org.apache.commons#commons-configuration2;2.0: not found
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve] :::: ERRORS
[ivy:retrieve]  SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/net/mikera/vectorz/0.48.0/vectorz-0.48.0.pom
[ivy:retrieve]  SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/net/mikera/vectorz/0.48.0/vectorz-0.48.0.jar
[ivy:retrieve]  SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.0/commons-configuration2-2.0.pom
[ivy:retrieve]  SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.0/commons-configuration2-2.0.jar
[ivy:retrieve] 
[ivy:retrieve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
```

BUG using ivy2.5.0:
```
improvisor:
     [java] Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
     [java]     at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
     [java]     at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
     [java]     at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
     [java]     at java.security.AccessController.doPrivileged(Native Method)
     [java]     at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
     [java]     at java.lang.Class.forName0(Native Method)
     [java]     at java.lang.Class.forName(Class.java:264)
     [java]     at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
     [java]     at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
     [java]     at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:132)
     [java]     at java.lang.Class.forName0(Native Method)
     [java]     at java.lang.Class.forName(Class.java:264)
     [java]     at java.awt.Toolkit$2.run(Toolkit.java:860)
     [java]     at java.awt.Toolkit$2.run(Toolkit.java:855)
     [java]     at java.security.AccessController.doPrivileged(Native Method)
     [java]     at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
     [java]     at imp.gui.ToolkitImages.<init>(ToolkitImages.java:131)
     [java]     at imp.gui.ToolkitImages.getInstance(ToolkitImages.java:122)
     [java]     at imp.ImproVisor.main(ImproVisor.java:502)
     [java] Java Result: 1

BUILD SUCCESSFUL
Total time: 11 seconds
```

**Comment by Eric-Chicot** [comment]
Hi,
If that's can you help
My environnement of development for Impro-visor is a qemu virtual machine with Debian 10 and xfce4, i changed the version ivy 2.5.0rc2 and i use Oracle JDK 8.
Perhaps a directive in your docker image?
